name: Deployments

on:
  push:
    tags:
      - "*"

jobs:
  apply-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: Rutger505-Org/kubernetes-infrastructure
          path: infrastructure

      - name: Setup Kubernetes
        uses: ./infrastructure/.github/actions/setup-kubernetes
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: OpenTofu Apply Cert Manager
        working-directory: ./0-cert-manager
        run: |
          tofu init
          tofu apply -input=false -auto-approve

      - name: OpenTofu Apply Cluster Issuers
        working-directory: ./1-cluster-issuers
        env:
          TF_VAR_cert_email: ${{ vars.CERT_EMAIL }}
        run: |
          tofu init
          tofu apply -input=false -auto-approve

      - name: OpenTofu Apply MetalLB
        working-directory: ./2-metallb
        env:
          TF_VAR_ip_addresses: ${{ vars.METALLB_IP_ADDRESSES }}
          TF_VAR_traefik_ip: ${{ vars.TRAEFIK_IP }}
        run: |
          tofu init
          tofu apply -input=false -auto-approve

      - name: OpenTofu Apply Pi-hole
        working-directory: ./3-pihole
        env:
          TF_VAR_pihole_web_ip: ${{ vars.PIHOLE_WEB_IP }}
          TF_VAR_pihole_dns_ip: ${{ vars.PIHOLE_DNS_IP }}
          TF_VAR_admin_password: ${{ secrets.PIHOLE_ADMIN_PASSWORD }}
        run: |
          tofu init
          tofu apply -input=false -auto-approve

